# Generated by Django 2.2.10 on 2020-07-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeSpacesRest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_disancing_violations',
            new_name='Social_distancing_violation',
        ),
    ]
