# Generated by Django 2.2.10 on 2020-07-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OfficeSpacesRest", "0003_announcements_attendance_mask_in_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(default="Icon.jpg", upload_to="Photos"),
        ),
    ]
