# Generated by Django 2.2.10 on 2020-08-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeSpacesRest', '0006_auto_20200826_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask_in_public',
            name='number_of_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='social_distancing_violation',
            name='number_of_violations',
            field=models.IntegerField(default=0),
        ),
    ]
