# Generated by Django 2.2.10 on 2020-09-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeSpacesRest', '0008_auto_20200831_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='outtime',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='intime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
