# Generated by Django 2.2.13 on 2020-09-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeSpacesRest', '0010_auto_20200913_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_distancing_violation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='social_distancing_violation',
            name='time',
            field=models.TimeField(),
        ),
    ]
