# Generated by Django 2.2.13 on 2020-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeSpacesRest', '0011_auto_20200914_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_distancing_violation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='social_distancing_violation',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
